name: Issue Auto Labeler

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: 이슈 라벨 자동 등록
        uses: actions/github-script@v7
        with:
          script: |
            let labels = [];
            const title = context.payload.issue.title.toLowerCase();
            if (title.includes('bug') || title.includes('오류')) labels.push('bug');
            if (title.includes('feature') || title.includes('기능')) labels.push('feature');
            if (title.includes('question') || title.includes('질문')) labels.push('question');
            if (labels.length === 0) labels.push('question');
            github.rest.issues.addLabels({
              issue_number: context.payload.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels
            }); 