name: Issue Auto Assigner

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: 이슈 작성자 자동 할당
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.payload.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [context.payload.issue.user.login]
            })

permissions:
  contents: write
  issues: write
  pull-requests: write 