name: PR Auto Labeler

on:
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: PR 라벨 자동 등록
        uses: actions/github-script@v7
        with:
          script: |
            const files = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            let labels = ['pr'];
            if (files.data.some(f => f.filename.startsWith('backend/'))) labels.push('backend');
            if (files.data.some(f => f.filename.startsWith('frontend/'))) labels.push('frontend');
            if (files.data.some(f => f.filename.startsWith('docs/'))) labels.push('docs');
            await github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels
            }); 

permissions:
  contents: write
  issues: write
  pull-requests: write 