name: PR Auto Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: PR 코드 리뷰어 자동 지정
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ['randywon']
            }) 